# Site settings
title: Open Humans Outreachy
email: support@openhumans.org
description: > # this means to ignore newlines until "baseurl:"
    The Open Humans Foundation (OHF) is a non-profit
    dedicated to empower individuals to use their own data to learn about themselves
    and facilitate new kinds of research, fostering new projects and data re-use.
    On this page, Open Humans coordinates its Outreachy participation.
baseurl: "/outreachy" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: OpenHumansOrg
theme: minima

# include: ['_historic']

# Build settings
markdown: kramdown

kramdown:
    auto_ids:   true
    toc_levels: 2..3
sass:
    sass_dir: assets
